name: Generate Statistic

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib

    - name: Run main.py
      run: python main.py

    - name: Push png to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output # Menggunakan branch output untuk menyimpan SVG
        build_dir: dist # Direktori tempat snake.svg disimpan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token untuk otorisasi push
