name: Generate SVG Reports and Update Medium Posts

on:
  schedule:
    - cron: '21 21 * * *'  # Runs daily at 5 AM WIB
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib numpy timedelta DateTime beautifulsoup4 pandas feedparser

      - name: Generate Statistic
        run: python main.py

      - name: Run the Medium script
        run: python medium.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md *.png
          git commit -m "Update SVG reports and Medium posts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
