name: Update GitHub Stats and Medium Posts

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run GitHub Stats Script
        run: python main.py

      - name: Run Medium Post Script
        run: python medium.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "dikaelsaputra2406@gmail.com"
          git add -A
          git commit -m "Update GitHub Stats and Medium Posts" || echo "No changes to commit"
          git push
