name: Run Python Scripts

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib

    - name: Run main.py
      run: python main.py

    - name: Upload GitHub Stats PNG
      uses: actions/upload-artifact@v3
      with:
        name: github_stats
        path: github_stats.png

    - name: Run medium.py
      run: python medium.py

    - name: Commit updated README
      uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        message: 'Update Medium posts in README'
