name: GitHub Profile Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib feedparser beautifulsoup4

    - name: Run main.py
      run: python main.py

    - name: Run medium.py
      run: |
           python medium.py || echo "Medium script failed"


    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update GitHub stats and Medium feed"
        git push origin main || echo "Error"
