name: Update GitHub Stats and Medium Posts

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch: # Jalankan secara manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib requests feedparser beautifulsoup4

    - name: Generate GitHub stats
      run: python main.py

    - name: Fetch Medium posts
      run: python medium.py

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update GitHub stats and Medium posts"
        git push
