name: Generate GitHub Stats Image

on:
  schedule:
    - cron: '21 20 * * *'
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install matplotlib requests

      - name: Run stats generator
        run: python main.py

      - name: Commit and push stats image
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update GitHub stats image'
          add: 'github_stats.png'
