name: Update Medium Posts

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests feedparser beautifulsoup4

      - name: Run medium.py script
        run: python medium.py

      - name: Commit and push README changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update Medium posts section in README.md'
          add: 'README.md'
