name: Update Medium Posts

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser beautifulsoup4

    - name: Run Medium
      run: python medium.py

    - name: Commit updated README
      uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        message: 'Update Medium posts in README'
