name: Generate Snake Animation

on:
  schedule:
    # At 21:00 on every day-of-week from Monday through Friday.
    - cron: "0 21 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: figuran04
          outputs: dist/snake.svg

      - name: Push the generated snake.svg to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
